service: 
    name: unfiltred-traffic
    
provider:
    name: aws
    runtime: python3.6
    stage: dev
    memorySize: 512
    timeout: 900
    environment:
        apikey: AQICAHhMz1Wf7tTGilIGlJZDb3LaCAXhS5a/i+jj8GeI1TQa6gEoEHnAjliRme2bM5w+NMpnAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMjirnZR8b5UBxgTZ6AgEQgDvrOPUAoMcP3RCIc0XmJp34GksbIXqzu1QPIZmRsMXga5yjj2FOANrEBR5scBxffHHHFM9WvWcbVSL23g==
        aws_region: us-east-1
        db_password: AQICAHhMz1Wf7tTGilIGlJZDb3LaCAXhS5a/i+jj8GeI1TQa6gHr01plcfbYdIgjaP8qeKxQAAAAbjBsBgkqhkiG9w0BBwagXzBdAgEAMFgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM/a9TjYHJeZITVsFiAgEQgCtHsOIot/7er7vqNlvKuPwsn5i0dHm+vN06f+1JR0UrBuNQz8L8jNofnNEs
        db_url: AQICAHhMz1Wf7tTGilIGlJZDb3LaCAXhS5a/i+jj8GeI1TQa6gHQuQO7vW3uvEq6M6eSJZRWAAAAljCBkwYJKoZIhvcNAQcGoIGFMIGCAgEAMH0GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM/5hbtKGk/bpYfcDpAgEQgFCGmwoxqJoKriZ3QRQLKH/OjtdJhQhzKN7AeRey2snliLdcN401RUu/WfN74QMOmC5dQPF/Qa6tp2MkJFj2nGG0sT7BPiCGvpZcI6/+yxO/7Q==
        db_user: AQICAHhMz1Wf7tTGilIGlJZDb3LaCAXhS5a/i+jj8GeI1TQa6gEbd4oY9yeRBPRVtPEl+aV8AAAAYjBgBgkqhkiG9w0BBwagUzBRAgEAMEwGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM6YP7mHs0FewhaW0WAgEQgB8xE0OQFJEZEncgtHEap2KURy1iro7i4T46sA+eFcWy
        recipients: andres.urrego@slalom.com,mithra.ramesh@slalom.com
        sender: noreply@cadillacfairview.tech
    

functions:
    dev_traffic_AL_to_raw:
        name: dev_traffic_AL_to_raw
        description: QA Script to Retrieve Data from Aislelabs
        handler: main.lambda_handler
        role: "arn:aws:iam::310064023253:role/service-role/customer_profile_AL_to_raw-role-xe2bqfm5"
        events:
         - http: 
               path: unfiltered-traffic
               method: post
               authorizer: aws_iam
               integration: lambda-proxy
               stage: dev
               request:
                parameters:
                  querystrings:
                    url: true

        
plugins:
  - serverless-python-requirements
